import '@testing-library/jest-dom'

// Mock stores
vi.mock('@stores', () => ({
  useClimateStore: vi.fn(() => ({
    climate: {
      axialTiltDegrees: 23.5,
      albedo: 0.3,
      greenhouseMultiplier: 1.0,
      currentTime: 0,
      yearLength: 365,
    },
    showTemperatureOverlay: false,
    setAxialTilt: vi.fn(),
    setAlbedo: vi.fn(),
    setGreenhouseMultiplier: vi.fn(),
    setCurrentTime: vi.fn(),
    setYearLength: vi.fn(),
    incrementTime: vi.fn(),
    toggleTemperatureOverlay: vi.fn(),
    setShowTemperatureOverlay: vi.fn(),
    reset: vi.fn(),
  })),
  selectClimateState: vi.fn(),
  selectAxialTilt: vi.fn(),
  selectAlbedo: vi.fn(),
  selectGreenhouseMultiplier: vi.fn(),
  selectCurrentTime: vi.fn(),
  selectYearLength: vi.fn(),
  selectShowTemperatureOverlay: vi.fn(),
  selectSeasonProgress: vi.fn(),
  useTerrainStore: vi.fn(() => ({
    seed: 12345,
    scale: 0.5,
    persistence: 0.5,
    lacunarity: 2.0,
    octaves: 6,
    waterLevel: 0.4,
    beachLevel: 0.42,
    plainsLevel: 0.55,
    hillsLevel: 0.75,
    setSeed: vi.fn(),
    setScale: vi.fn(),
    setPersistence: vi.fn(),
    setLacunarity: vi.fn(),
    setOctaves: vi.fn(),
    setWaterLevel: vi.fn(),
    setBeachLevel: vi.fn(),
    setPlainsLevel: vi.fn(),
    setHillsLevel: vi.fn(),
    randomizeSeed: vi.fn(),
    reset: vi.fn(),
  })),
  selectSeed: vi.fn(),
  selectScale: vi.fn(),
  selectPersistence: vi.fn(),
  selectLacunarity: vi.fn(),
  selectOctaves: vi.fn(),
  selectWaterLevel: vi.fn(),
  selectBeachLevel: vi.fn(),
  selectPlainsLevel: vi.fn(),
  selectHillsLevel: vi.fn(),
  useCameraStore: vi.fn(() => ({
    rotateSensitivity: 0.85,
    zoomSensitivity: 0.75,
    panSensitivity: 0.5,
    dampingFactor: 0.08,
    invertHorizontalAxis: false,
    invertVerticalAxis: false,
    setRotateSensitivity: vi.fn(),
    setZoomSensitivity: vi.fn(),
    setPanSensitivity: vi.fn(),
    setDampingFactor: vi.fn(),
    setInvertHorizontalAxis: vi.fn(),
    setInvertVerticalAxis: vi.fn(),
    reset: vi.fn(),
  })),
  selectCameraSettings: vi.fn(),
  usePlanetStore: vi.fn(() => ({
    planet: {
      version: 1,
      atmosphere: { gases: [], surfacePressureKPa: 101.325, greenhouseCoefficient: 0.3 },
      geology: {
        plates: [],
        heightField: { width: 64, height: 32, unit: 'meters', values: [] },
        volcanismIndex: 0,
      },
      hydrology: {
        oceanCoverage: 0.72,
        rivers: { seed: null, systems: [] },
        iceCaps: { northCoverageFraction: 0.05, southCoverageFraction: 0.04 },
      },
      biosphere: { biomeMap: { width: 64, height: 32, cells: [] }, biodiversityIndex: 0.1 },
      civilization: { populations: [], techLevel: 'none', pollutionIndex: 0 },
      climate: {
        axialTiltDegrees: 23.5,
        albedo: 0.3,
        greenhouseMultiplier: 1.0,
        currentTime: 0,
        yearLength: 365,
      },
    },
    lastLoadedSlot: null,
    setPlanetState: vi.fn(),
    reset: vi.fn(),
  })),
  selectPlanetState: vi.fn(),
  selectPlanetLastLoadedSlot: vi.fn(),
  useSettingsStore: vi.fn(() => ({
    loadLastSaveOnStartup: false,
    setLoadLastSaveOnStartup: vi.fn(),
  })),
  selectLoadLastSaveOnStartup: vi.fn(),
  useSimulationStore: vi.fn(() => ({
    speed: 1,
    isPaused: false,
    setSpeed: vi.fn(),
    setIsPaused: vi.fn(),
    hydrateFromScheduler: vi.fn(),
  })),
  useNotificationStore: vi.fn(() => ({
    notifications: [],
    addNotification: vi.fn(),
    removeNotification: vi.fn(),
    clearNotifications: vi.fn(),
  })),
  useUIStore: vi.fn(() => ({
    showDevMenu: false,
    toggleDevMenu: vi.fn(),
    setShowDevMenu: vi.fn(),
  })),
}))

// Mock Three.js for testing
vi.mock('three', () => ({
  WebGLRenderer: vi.fn(() => ({
    setSize: vi.fn(),
    setPixelRatio: vi.fn(),
    render: vi.fn(),
    dispose: vi.fn(),
    domElement: document.createElement('canvas'),
  })),
  Scene: vi.fn(() => ({
    add: vi.fn(),
    remove: vi.fn(),
  })),
  PerspectiveCamera: vi.fn(() => ({
    position: { set: vi.fn() },
    lookAt: vi.fn(),
    updateProjectionMatrix: vi.fn(),
  })),
  SphereGeometry: vi.fn(),
  MeshBasicMaterial: vi.fn(),
  Mesh: vi.fn(() => ({
    rotation: { x: 0, y: 0, z: 0 },
  })),
  Vector2: vi.fn(),
  Clock: vi.fn(() => ({
    getDelta: vi.fn(() => 0.016),
  })),
}))

// Mock canvas context
Object.defineProperty(HTMLCanvasElement.prototype, 'getContext', {
  value: vi.fn(() => ({
    clearRect: vi.fn(),
    fillRect: vi.fn(),
    getImageData: vi.fn(() => ({ data: new Array(4) })),
    putImageData: vi.fn(),
    createImageData: vi.fn(() => ({ data: new Array(4) })),
    setTransform: vi.fn(),
    drawImage: vi.fn(),
    save: vi.fn(),
    fillText: vi.fn(),
    restore: vi.fn(),
    beginPath: vi.fn(),
    moveTo: vi.fn(),
    lineTo: vi.fn(),
    closePath: vi.fn(),
    stroke: vi.fn(),
    translate: vi.fn(),
    scale: vi.fn(),
    rotate: vi.fn(),
    arc: vi.fn(),
    fill: vi.fn(),
    measureText: vi.fn(() => ({ width: 0 })),
    transform: vi.fn(),
    rect: vi.fn(),
    clip: vi.fn(),
  })),
  writable: true,
})
